services:
  mastra-101:
    image: mikesprague/mastra-101:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 4111:4111
